
/**
* _FileInterfaceStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FileInterface.idl
* jueves 20 de mayo de 2021 07:43:29 PM GMT
*/

public class _FileInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements FileInterface
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _FileInterfaceStub ()
  {
    super ();
  }

  public _FileInterfaceStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public byte[] downloadFile (String fileName)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("downloadFile", true);
       _out.write_string (fileName);
       _in = _invoke (_out);
       byte __result[] = FileInterfacePackage.DataHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return downloadFile (fileName);
    } finally {
        _releaseReply (_in);
    }
  } // downloadFile

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _FileInterfaceStub
