
/**
* FileInterfaceHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FileInterface.idl
* jueves 20 de mayo de 2021 07:56:31 PM GMT
*/

abstract public class FileInterfaceHelper
{
  private static String  _id = "IDL:FileInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FileInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileInterfaceHelper.id (), "FileInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileInterface)
      return (FileInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new _FileInterfaceStub (delegate);
    }
  }

}
