
/**
* FileInterfaceOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FileInterface.idl
* jueves 20 de mayo de 2021 07:43:29 PM GMT
*/

public interface FileInterfaceOperations 
{
  byte[] downloadFile (String fileName);
} // interface FileInterfaceOperations
