package FileInterfacePackage;


/**
* FileInterfacePackage/DataHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FileInterface.idl
* jueves 20 de mayo de 2021 07:43:29 PM GMT
*/

public final class DataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public DataHolder ()
  {
  }

  public DataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileInterfacePackage.DataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileInterfacePackage.DataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileInterfacePackage.DataHelper.type ();
  }

}
